version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-rs
    ports:
      - 27017:27017
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

