services:
  postgres:
    image: postgres:latest
    container_name: loyalty_postgres
    environment:
      POSTGRES_DB: LOYALTY_PROGRAM
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loyalty-network

  mongodb:
    image: mongo:latest
    container_name: loyalty_mongodb
    environment:
      MONGO_INITDB_DATABASE: LOYALTY_PROGRAM
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - loyalty-network

volumes:
  pgdata:
  mongodbdata:

networks:
  loyalty-network:
