version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: order_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ORDER_API
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
